/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_jafetmorel;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author 24661
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_doc = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_doc = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cb_equipo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cb_coop = new javax.swing.JComboBox<>();
        cb_part = new javax.swing.JComboBox<>();
        cb_nota = new javax.swing.JComboBox<>();
        sp_general = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jd_al = new javax.swing.JDialog();
        tabbed_alumnos = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_pruebas = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        tf_alnom = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_alap = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_alus = new javax.swing.JTextField();
        tf_alpw = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tf_alid = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        sp_alaño = new javax.swing.JSpinner();
        sp_alclases = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jd_dec = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_dec = new javax.swing.JTree();
        popup = new javax.swing.JPopupMenu();
        el = new javax.swing.JMenuItem();
        lis = new javax.swing.JMenuItem();
        mod = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jb_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_loginus = new javax.swing.JTextField();
        tf_loginpw = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        tabbedpane_reg = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_regceopreg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_regceoid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sp_regexp = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        sp_regceoedad = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sp_regdecedad = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        tf_regdecpreg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_regdecid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_regtitun = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_regtitmadec = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tf_regdocpreg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_regtitmadoc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_regnomclase = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sp_regal = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_regdesc = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        sp_regaño = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        sp_regclases = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        tf_regcuenta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_regnom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_regap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_reguser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_regpw = new javax.swing.JPasswordField();
        jb_reg = new javax.swing.JButton();

        lista_doc.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(lista_doc);

        jLabel24.setText("Lista de alumnos:");

        jLabel25.setText("Trabajo en equipo:");

        cb_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bien", "Regular", "Mejorable" }));

        jLabel26.setText("Cooperación:");

        jLabel27.setText("Participación:");

        jLabel28.setText("Evaluación de nota:");

        jLabel29.setText("Evaluación general:");

        cb_coop.setModel(cb_equipo.getModel());

        cb_part.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Moderada", "Excelente" }));

        cb_nota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobado", "Reprobado" }));
        cb_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_notaActionPerformed(evt);
            }
        });

        sp_general.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jButton1.setText("Evaluar alumno");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_docLayout = new javax.swing.GroupLayout(jd_doc.getContentPane());
        jd_doc.getContentPane().setLayout(jd_docLayout);
        jd_docLayout.setHorizontalGroup(
            jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_docLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jd_docLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(85, 85, 85)
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_docLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(195, 195, 195))
        );
        jd_docLayout.setVerticalGroup(
            jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_docLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_docLayout.createSequentialGroup()
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(cb_coop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(cb_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cb_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jd_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(sp_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tabbed_alumnos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbed_alumnosStateChanged(evt);
            }
        });

        table_pruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trabajo en equipo", "Cooperación", "Participación", "Evaluación de nota", "Evaluación general", "Docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_pruebas);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        tabbed_alumnos.addTab("Pruebas", jPanel7);

        jLabel30.setText("Nombre:");

        tf_alnom.setText("jTextField1");

        jLabel31.setText("Apellido");

        tf_alap.setText("jTextField2");

        jLabel32.setText("Usuario:");

        jLabel33.setText("Contraseña:");

        tf_alus.setText("jTextField3");

        tf_alpw.setText("jTextField4");

        jLabel34.setText("Numero de cuenta:");

        tf_alid.setText("jTextField5");

        jLabel35.setText("Año de carrera");

        jLabel36.setText("Cantidad de clases");

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addGap(5, 5, 5))
                                        .addComponent(jLabel30)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_alus, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(tf_alpw))
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_alap)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(tf_alnom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel36))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_alid, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sp_alclases, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                        .addComponent(sp_alaño, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButton2)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_alnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_alap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_alus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_alpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_alid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(sp_alaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(sp_alclases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
        );

        tabbed_alumnos.addTab("Información general", jPanel8);

        javax.swing.GroupLayout jd_alLayout = new javax.swing.GroupLayout(jd_al.getContentPane());
        jd_al.getContentPane().setLayout(jd_alLayout);
        jd_alLayout.setHorizontalGroup(
            jd_alLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_alLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed_alumnos)
                .addContainerGap())
        );
        jd_alLayout.setVerticalGroup(
            jd_alLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_alLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed_alumnos)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Docentes");
        jt_dec.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_dec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_decMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jt_dec);

        javax.swing.GroupLayout jd_decLayout = new javax.swing.GroupLayout(jd_dec.getContentPane());
        jd_dec.getContentPane().setLayout(jd_decLayout);
        jd_decLayout.setHorizontalGroup(
            jd_decLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_decLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_decLayout.setVerticalGroup(
            jd_decLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_decLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        el.setText("Eliminar");
        el.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elMouseClicked(evt);
            }
        });
        popup.add(el);

        lis.setText("listar");
        popup.add(lis);

        mod.setText("Modificar");
        popup.add(mod);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_login.setText("Ingresar");
        jb_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_loginActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_loginus, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(tf_loginpw)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_loginus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_loginpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel1);

        jLabel7.setText("Título de pregrado:");

        jLabel8.setText("Numero de identidad:");

        jLabel9.setText("Años de experiencia");

        sp_regexp.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setText("Edad:");

        sp_regceoedad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(tf_regceopreg))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(sp_regexp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(sp_regceoedad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(tf_regceoid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_regceopreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_regceoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_regexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(sp_regceoedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        tabbedpane_reg.addTab("CEO", jPanel4);

        jLabel11.setText("Edad:");

        sp_regdecedad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel12.setText("Título de pregrado:");

        jLabel13.setText("Numero de identidad:");

        jLabel14.setText("Título universitario:");

        jLabel15.setText("TItulo de maestría:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(29, 29, 29)
                                .addComponent(tf_regdecpreg))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(tf_regdecid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(166, 166, 166))
                                    .addComponent(tf_regtitun)
                                    .addComponent(tf_regtitmadec)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addComponent(sp_regdecedad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_regdecpreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_regdecid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_regtitun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_regtitmadec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(sp_regdecedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedpane_reg.addTab("Decano", jPanel5);

        jLabel16.setText("Título de pregrado:");

        jLabel17.setText("TItulo de maestría:");

        jLabel18.setText("Nombre de la clase:");

        jLabel19.setText("Cantidad de alumnos en la clase");

        sp_regal.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel20.setText("Descripción de la clase:");

        ta_regdesc.setColumns(20);
        ta_regdesc.setRows(5);
        jScrollPane1.setViewportView(ta_regdesc);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(tf_regdocpreg)
                    .addComponent(tf_regtitmadoc)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sp_regal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_regnomclase))
                .addGap(104, 104, 104))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_regdocpreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_regtitmadoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_regnomclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sp_regal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedpane_reg.addTab("Docente", jPanel6);

        sp_regaño.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel21.setText("Cantidad de clases que faltan");

        sp_regclases.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel22.setText("Numero de cuenta:");

        jLabel23.setText("Años de la carrera que cursa:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel22)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addGap(40, 40, 40)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_regclases, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_regaño, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_regcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_regcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_regaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_regclases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        tabbedpane_reg.addTab("Alumno", jPanel3);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Usuario:");

        tf_reguser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_reguserActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña");

        jb_reg.setText("Registrarse");
        jb_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane_reg, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_regap)
                            .addComponent(tf_regnom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_regpw)
                            .addComponent(tf_reguser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jb_reg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_regnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_reguser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_regap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tf_regpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(tabbedpane_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_reg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_loginActionPerformed
        // TODO add your handling code here:
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ningún usuario ingresado.");
        } else {
            int aux = 0;
            for (int i = 0; i < usuarios.size(); i++) {
                if (usuarios.get(i).getUsuario().equals(tf_loginus.getText()) & usuarios.get(i).getContraseña().equals(tf_loginpw.getText())) {
                    if (usuarios.get(i) instanceof CEO) {
                        aux++;

                        break;
                    } else if (usuarios.get(i) instanceof Decano) {
                        aux++;
                        DefaultTreeModel model = (DefaultTreeModel) jt_dec.getModel();
                        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();
                        for (int j = 0; j < usuarios.size(); j++) {
                            if (usuarios.get(j) instanceof Docente) {
                                DefaultMutableTreeNode docente = new DefaultMutableTreeNode(usuarios.get(j));
                                for (int k = 0; k < ((Docente) usuarios.get(j)).getAlumnos().size(); k++) {
                                    DefaultMutableTreeNode alumno = new DefaultMutableTreeNode(((Docente) usuarios.get(j)).getAlumnos().get(i));
                                    docente.add(alumno);
                                }
                                raiz.add(docente);
                            }
                        }
                        model.reload();
                        jt_dec.setModel(model);
                        mostrardec();
                        break;
                    } else if (usuarios.get(i) instanceof Docente) {
                        aux++;
                        DefaultListModel modelo = (DefaultListModel) lista_doc.getModel();
                        for (int j = 0; j < usuarios.size(); j++) {
                            if (usuarios.get(j) instanceof Alumnos) {
                                modelo.addElement(usuarios.get(j));
                            }
                        }
                        lista_doc.setModel(modelo);
                        doc = (Docente) usuarios.get(i);
                        mostrardocente();
                        break;
                    } else if (usuarios.get(i) instanceof Alumnos) {
                        aux++;
                        al = (Alumnos) usuarios.get(i);
                        DefaultTableModel model = (DefaultTableModel) table_pruebas.getModel();
                        model.setRowCount(0);
                        for (int j = 0; j < al.getPruebas().size(); j++) {
                            Object[] row = {al.getPruebas().get(j).getEquipo(), al.getPruebas().get(j).getCoop(), al.getPruebas().get(j).getParticipacion(), al.getPruebas().get(j).getNota(), al.getPruebas().get(j).getGeneral(), al.getPruebas().get(j).getDocente()};
                            model.addRow(row);
                        }
                        table_pruebas.setModel(model);
                        mostraral();
                        break;
                    }
                }
            }
            if (aux == 0) {
                JOptionPane.showMessageDialog(this, "Nombre de usuario y/o contraseña incorrecta.");
            }
        }
        tf_loginus.setText("");
        tf_loginpw.setText("");
    }//GEN-LAST:event_jb_loginActionPerformed

    private void tf_reguserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_reguserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_reguserActionPerformed

    private void jb_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regActionPerformed
        // TODO add your handling code here:
        String nombre = tf_regnom.getText(), apellido = tf_regap.getText(), user = tf_reguser.getText(), pw = tf_regpw.getText();
        if (tabbedpane_reg.getSelectedIndex() == 0) {
            usuarios.add(new CEO(tf_regceopreg.getText(), Integer.parseInt(tf_regceoid.getText()), (int) sp_regexp.getValue(), (int) sp_regceoedad.getValue(), user, pw, nombre, apellido));
            tf_regceopreg.setText("");
            tf_regceoid.setText("");
            sp_regexp.setValue(0);
            sp_regceoedad.setValue(0);
        } else if (tabbedpane_reg.getSelectedIndex() == 1) {
            usuarios.add(new Decano(tf_regdecpreg.getText(), Integer.parseInt(tf_regceoid.getText()), (int) sp_regdecedad.getValue(), tf_regtitun.getText(), tf_regtitmadec.getText(), user, pw, nombre, apellido));
            tf_regdecpreg.setText("");
            tf_regceoid.setText("");
            sp_regdecedad.setValue(0);
            tf_regtitun.setText("");
            tf_regtitmadec.setText("");
        } else if (tabbedpane_reg.getSelectedIndex() == 2) {
            usuarios.add(new Docente(tf_regdocpreg.getText(), tf_regtitmadoc.getText(), (int) sp_regal.getValue(), tf_regnomclase.getText(), ta_regdesc.getText(), user, pw, nombre, apellido));
            tf_regdocpreg.setText("");
            tf_regtitmadoc.setText("");
            sp_regal.setValue(0);
            tf_regnomclase.setText("");
            ta_regdesc.setText("");
        } else if (tabbedpane_reg.getSelectedIndex() == 3) {
            usuarios.add(new Alumnos(Integer.parseInt(tf_regcuenta.getText()), (int) sp_regaño.getValue(), (int) sp_regclases.getValue(), user, pw, nombre, apellido));
            tf_regcuenta.setText("");
            sp_regaño.setValue(0);
            sp_regclases.setValue(0);
        }
        tf_regnom.setText("");
        tf_regap.setText("");
        tf_reguser.setText("");
        tf_regpw.setText("");
    }//GEN-LAST:event_jb_regActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (lista_doc.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) lista_doc.getModel();
            for (int i = 0; i < usuarios.size(); i++) {
                if (usuarios.get(i).equals((Persona) modelo.get(lista_doc.getSelectedIndex()))) {
                    ((Alumnos) usuarios.get(i)).getPruebas().add(new Prueba((String) cb_equipo.getSelectedItem(), (String) cb_coop.getSelectedItem(), (String) cb_part.getSelectedItem(), (String) cb_nota.getSelectedItem(), (int) sp_general.getValue(), doc));
                    JOptionPane.showMessageDialog(this, "Prueba agregada con éxito.");
                    for (int j = 0; j < usuarios.size(); j++) {
                        if (usuarios.get(j).equals(doc)) {
                            ((Docente) usuarios.get(i)).getAlumnos().add((Alumnos) usuarios.get(i));
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void tabbed_alumnosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbed_alumnosStateChanged
        // TODO add your handling code here:
        if (usuarios.isEmpty() == false) {
            if (tabbed_alumnos.getSelectedIndex() == 1) {
                tf_alnom.setText(al.getNombre());
                tf_alap.setText(al.getApellido());
                tf_alus.setText(al.getUsuario());
                tf_alpw.setText(al.getContraseña());

                tf_alid.setText("" + al.getCuenta());
                sp_alclases.setValue(al.getClases());
                sp_alaño.setValue(al.getAño());
            }
        }
    }//GEN-LAST:event_tabbed_alumnosStateChanged

    private void cb_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_notaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < usuarios.size(); i++) {
            if (((Alumnos) usuarios.get(i)).equals(al)) {
                ((Alumnos) usuarios.get(i)).setUsuario(tf_alus.getText());
                ((Alumnos) usuarios.get(i)).setContraseña(tf_alpw.getText());
                ((Alumnos) usuarios.get(i)).setNombre(tf_alnom.getText());
                ((Alumnos) usuarios.get(i)).setApellido(tf_alap.getText());
                ((Alumnos) usuarios.get(i)).setCuenta(Integer.parseInt(tf_alid.getText()));
                ((Alumnos) usuarios.get(i)).setClases((int) sp_alclases.getValue());
                ((Alumnos) usuarios.get(i)).setAño((int) sp_alaño.getValue());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jt_decMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_decMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_dec.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_dec.setSelectionRow(row);
            Object v1
                    = jt_dec.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada
                        = (Persona) nodo_seleccionado.
                                getUserObject();
                popup.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_decMouseClicked

    private void elMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elMouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_dec.getModel();
        m.removeNodeFromParent(
                nodo_seleccionado);
        m.reload();
        usuarios.remove((Persona)nodo_seleccionado.getUserObject());
        
    }//GEN-LAST:event_elMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void mostrardocente() {
        jd_doc.setModal(true);
        jd_doc.pack();
        jd_doc.setLocationRelativeTo(this);
        jd_doc.setVisible(true);
    }

    public void mostraral() {
        jd_al.setModal(true);
        jd_al.pack();
        jd_al.setLocationRelativeTo(this);
        jd_al.setVisible(true);
    }

    public void mostrardec() {
        jd_dec.setModal(true);
        jd_dec.pack();
        jd_dec.setLocationRelativeTo(this);
        jd_dec.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_coop;
    private javax.swing.JComboBox<String> cb_equipo;
    private javax.swing.JComboBox<String> cb_nota;
    private javax.swing.JComboBox<String> cb_part;
    private javax.swing.JMenuItem el;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_reg;
    private javax.swing.JDialog jd_al;
    private javax.swing.JDialog jd_dec;
    private javax.swing.JDialog jd_doc;
    private javax.swing.JTree jt_dec;
    private javax.swing.JMenuItem lis;
    private javax.swing.JList<String> lista_doc;
    private javax.swing.JMenuItem mod;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JSpinner sp_alaño;
    private javax.swing.JSpinner sp_alclases;
    private javax.swing.JSpinner sp_general;
    private javax.swing.JSpinner sp_regal;
    private javax.swing.JSpinner sp_regaño;
    private javax.swing.JSpinner sp_regceoedad;
    private javax.swing.JSpinner sp_regclases;
    private javax.swing.JSpinner sp_regdecedad;
    private javax.swing.JSpinner sp_regexp;
    private javax.swing.JTextArea ta_regdesc;
    private javax.swing.JTabbedPane tabbed_alumnos;
    private javax.swing.JTabbedPane tabbedpane_reg;
    private javax.swing.JTable table_pruebas;
    private javax.swing.JTextField tf_alap;
    private javax.swing.JTextField tf_alid;
    private javax.swing.JTextField tf_alnom;
    private javax.swing.JTextField tf_alpw;
    private javax.swing.JTextField tf_alus;
    private javax.swing.JPasswordField tf_loginpw;
    private javax.swing.JTextField tf_loginus;
    private javax.swing.JTextField tf_regap;
    private javax.swing.JTextField tf_regceoid;
    private javax.swing.JTextField tf_regceopreg;
    private javax.swing.JTextField tf_regcuenta;
    private javax.swing.JTextField tf_regdecid;
    private javax.swing.JTextField tf_regdecpreg;
    private javax.swing.JTextField tf_regdocpreg;
    private javax.swing.JTextField tf_regnom;
    private javax.swing.JTextField tf_regnomclase;
    private javax.swing.JPasswordField tf_regpw;
    private javax.swing.JTextField tf_regtitmadec;
    private javax.swing.JTextField tf_regtitmadoc;
    private javax.swing.JTextField tf_regtitun;
    private javax.swing.JTextField tf_reguser;
    // End of variables declaration//GEN-END:variables
    ArrayList<Persona> usuarios = new ArrayList();
    Docente doc;
    Alumnos al;
    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;
}
